CourseManagement/ShopManagement/Models/CourseModels/branch.cs
namespace CourseManagement.Models.CourseModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("branchs")]
    public partial class branch
    {
        public long id { get; set; }

        [StringLength(100)]
        public string branch_name { get; set; }

        public string address { get; set; }

        [StringLength(50)]
        public string phone_number { get; set; }

        [StringLength(50)]
        public string email { get; set; }
    }
}

CourseManagement/ShopManagement/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagement.Models.CourseModels;
using CourseManagement.Models;

namespace CourseManagement.Controllers
{
    public class BranchController : Controller
    {
        private CoureseContext db = new CoureseContext();

        // GET: Branch
        public ActionResult Index()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }

            return View(db.branchs.ToList());
        }

        // GET: Branch/Details/5
        public ActionResult Details(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            branch branch = db.branchs.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // GET: Branch/Create
        public ActionResult Create()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            return View();
        }

        // POST: Branch/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,branch_name,address,phone_number,email")] branch branch)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (ModelState.IsValid)
            {
                db.branchs.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        // GET: Branch/Edit/5
        public ActionResult Edit(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            branch branch = db.branchs.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branch/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,branch_name,address,phone_number,email")] branch branch)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (ModelState.IsValid)
            {
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branch/Delete/5
        public ActionResult Delete(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            branch branch = db.branchs.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            branch branch = db.branchs.Find(id);
            db.branchs.Remove(branch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagement/ShopManagement/Views/Branch/Create.cshtml
@model CourseManagement.Models.CourseModels.branch

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-center">
                @using (Html.BeginForm("Create", "Branch", FormMethod.Post, new { @class = "w-100" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.branch_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.branch_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.branch_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>*@

                    <div class="form-group row pt-2">
                        <div class="col-md-offset-2 col-md-10 text-center">
                            <input type="submit" value="Create" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                        </div>

                    </div>
                </div>
                }
            </div>
        </div>
    </div>

</div>

CourseManagement/ShopManagement/Views/Branch/Delete.cshtml
@model CourseManagement.Models.CourseModels.branch

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Delete</h6>
            <h3>Are you sure you want to delete this?</h3>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-center">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.branch_name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.branch_name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.phone_number)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.phone_number)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>
                    <p>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                        }
                    </p>
                </dl>


            </div>
        </div>
    </div>

</div>

CourseManagement/ShopManagement/Views/Branch/Details.cshtml
@model CourseManagement.Models.CourseModels.branch

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Details</h6>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-center">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.branch_name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.branch_name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.phone_number)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.phone_number)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.email)
                    </dd>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                    </p>
                </dl>


            </div>
        </div>
    </div>

</div>

CourseManagement/ShopManagement/Views/Branch/Edit.cshtml
@model CourseManagement.Models.CourseModels.branch

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Edit Category</h6>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-center">
                @using (Html.BeginForm("Edit", "Branch", FormMethod.Post, new { @class = "w-100" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.id)
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.branch_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.branch_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.branch_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
                        </div>
                      
                    </div>
                </div>
                }
            </div>
        </div>
    </div>

</div>

CourseManagement/ShopManagement/Views/Branch/Index.cshtml
@model IEnumerable<CourseManagement.Models.CourseModels.branch>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"></h1>
        <a href="@Url.Action("Create", "Branch")" class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Create New</a>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Branch List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.branch_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.address)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.phone_number)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.email)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot class="thead-dark">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.branch_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.address)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.phone_number)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.email)
                            </th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                @Html.DisplayFor(modelItem => item.branch_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.address)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.phone_number)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.email)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Branch", new { id = item.id })" class="btn btn-info">
                                        <span class="fa fa-edit"></span> Edit
                                    </a>
                                    <a href="@Url.Action("Details", "Branch", new { id = item.id })" class="btn btn-info">
                                        <span class="fa fa-eye"></span> Details
                                    </a>
                                    <a href="@Url.Action("Delete", "Branch", new { id = item.id })" class="btn btn-danger">
                                        <span class="fa fa-trash"></span> Delete
                                    </a>
                              
                                </td>
                          
                            </tr>
                        }
                    </tbody>
                </table>
                <br />
           
            </div>
        </div>
    </div>
</div>