CourseManagement/ShopManagement/Controllers/CourseStudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagement.Models.CourseModels;
using CourseManagement.Models;
using Rotativa;

namespace CourseManagement.Controllers
{
    public class CourseStudentController : Controller
    {
        private CoureseContext db = new CoureseContext();

        // GET: CourseStudent
        public ActionResult Index(String name = "")
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            var courses_student = db.courses_student.Include(c => c.cours).Include(c => c.courses_type).Include(c => c.student).Where(a => a.score == null 
            && (a.student.student_name.Contains(name) || a.cours.course_name.Contains(name) || a.student.student_code.Contains(name) ) );
            return View(courses_student.ToList());
        }

        public ActionResult PrintPDF()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            List<courses_student> Data = db.courses_student.Where(a => a.score == null).ToList();

            return new PartialViewAsPdf("PrintPDF", Data)
            {
                FileName = "TestPartialViewAsPdf.pdf"
            };
        }

        // GET: CourseStudent/Details/5
        public ActionResult Details(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            courses_student courses_student = db.courses_student.Find(id);
            if (courses_student == null)
            {
                return HttpNotFound();
            }
            return View(courses_student);
        }

        // GET: CourseStudent/Create
        public ActionResult Create()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            ViewBag.course_id = new SelectList(db.courses, "id", "course_name");
            ViewBag.course_type_id = new SelectList(db.courses_type, "id", "name");
            ViewBag.student_id = new SelectList(db.students, "id", "student_code");
            return View();
        }

        // POST: CourseStudent/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,student_id,course_id,course_type_id,score")] courses_student courses_student)
        {
            if (ModelState.IsValid)
            {
                db.courses_student.Add(courses_student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.course_id = new SelectList(db.courses, "id", "course_name", courses_student.course_id);
            ViewBag.course_type_id = new SelectList(db.courses_type, "id", "name", courses_student.course_type_id);
            ViewBag.student_id = new SelectList(db.students, "id", "student_code", courses_student.student_id);
            return View(courses_student);
        }

        // GET: CourseStudent/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            courses_student courses_student = db.courses_student.Find(id);
            if (courses_student == null)
            {
                return HttpNotFound();
            }
            ViewBag.course_id = new SelectList(db.courses, "id", "course_name", courses_student.course_id);
            ViewBag.course_type_id = new SelectList(db.courses_type, "id", "name", courses_student.course_type_id);
            ViewBag.student_id = new SelectList(db.students, "id", "student_code", courses_student.student_id);
            return View(courses_student);
        }

        // POST: CourseStudent/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,student_id,course_id,course_type_id,score")] courses_student courses_student)
        {
            if (ModelState.IsValid)
            {
                if(courses_student.score <= 70)
                {
                    courses_student.course_type_id = 1;
                } else
                {
                    courses_student.course_type_id = 2;
                }
                db.Entry(courses_student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.course_id = new SelectList(db.courses, "id", "course_name", courses_student.course_id);
            ViewBag.course_type_id = new SelectList(db.courses_type, "id", "name", courses_student.course_type_id);
            ViewBag.student_id = new SelectList(db.students, "id", "student_code", courses_student.student_id);
            return View(courses_student);
        }

        // GET: CourseStudent/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            courses_student courses_student = db.courses_student.Find(id);
            if (courses_student == null)
            {
                return HttpNotFound();
            }
            return View(courses_student);
        }

        // POST: CourseStudent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            courses_student courses_student = db.courses_student.Find(id);
            db.courses_student.Remove(courses_student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagement/ShopManagement/Views/CourseStudent/Create.cshtml
@model CourseManagement.Models.CourseModels.courses_student

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>courses_student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.student_id, "student_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("student_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.student_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.course_id, "course_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("course_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.course_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.course_type_id, "course_type_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("course_type_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.course_type_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CourseManagement/ShopManagement/Views/CourseStudent/Delete.cshtml
@model CourseManagement.Models.CourseModels.courses_student

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>courses_student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cours.course_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cours.course_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.courses_type.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.courses_type.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.student_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.student_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.score)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CourseManagement/ShopManagement/Views/CourseStudent/Details.cshtml
@model CourseManagement.Models.CourseModels.courses_student

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>courses_student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cours.course_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cours.course_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.courses_type.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.courses_type.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.student_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.student_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.score)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CourseManagement/ShopManagement/Views/CourseStudent/Edit.cshtml
@model CourseManagement.Models.CourseModels.courses_student

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>courses_student</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.student_id)
    @Html.HiddenFor(model => model.course_id)
    <div class="form-group">
        @Html.LabelFor(model => model.student_id, "student_id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("student_id", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.student_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.course_id, "course_id", htmlAttributes: new { @class = "control-label col-md-2", @disabled = "disabled" })
        <div class="col-md-10">
            @Html.DropDownList("course_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.course_id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.score, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.score, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.score, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CourseManagement/ShopManagement/Views/CourseStudent/Index.cshtml
@model IEnumerable<CourseManagement.Models.CourseModels.courses_student>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800"></h1>
        <a href="@Url.Action("PrintPDF", "CourseStudent")" class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Export Student </a>
        
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <form method="get" action="@Url.Action("Index")">
                <div class="form-group form-inline">
                    <input type="text" name="name" class="form-control" placeholder="Input your keyword" />
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>

            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-dark">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.cours.course_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.student.student_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.student.student_code)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.courses_type.name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.score)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot class="thead-dark">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.cours.course_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.student.student_name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.student.student_code)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.courses_type.name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.score)
                            </th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.cours.course_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.student.student_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.student.student_code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.courses_type.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.score)
                            </td>
                            <td>
                                @if (item.score == null)
                                {
                                    <a href="@Url.Action("Edit", "CourseStudent", new { id = item.id })" class="btn btn-info">
                                        <span class="fa fa-edit"></span> Mark
                                    </a>
                                }

                                @*<a href="@Url.Action("Details", "CourseStudent", new { id = item.id })" class="btn btn-info">
                                    <span class="fa fa-eye"></span> Details
                                </a>
                                <a href="@Url.Action("Delete", "CourseStudent", new { id = item.id })" class="btn btn-danger">
                                    <span class="fa fa-trash"></span> Delete
                                </a>*@

                            </td>

                        </tr>
                        }
                    </tbody>
                </table>
                <br />

            </div>
        </div>
    </div>
</div>

CourseManagement/ShopManagement/Views/CourseStudent/PrintPDF.cshtml
@model IEnumerable<CourseManagement.Models.CourseModels.courses_student>

<style>
    thead {
        background-color: black;
        color: white
    }

    table {
        border: 1px solid black;
    }

    td, th {
        padding: 5px;
        font-size: 14px;
    }
</style>

<table class="table table-bordered table-striped" border="1" style="border-color:black">
    <thead>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Course name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.student.student_name</td>
            <td>@item.student.phone_number</td>
            <td>@item.student.email</td>
            <td>@item.cours.course_name</td>

        </tr>

        }
    </tbody>
</table>  