CourseManagement/ShopManagement/Models/CourseModels/question.cs
namespace CourseManagement.Models.CourseModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class question
    {
        public long id { get; set; }

        public string question_name { get; set; }

        [Column(TypeName = "text")]
        public string description { get; set; }
    }
}

CourseManagement/ShopManagement/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagement.Models.CourseModels;
using CourseManagement.Models;

namespace CourseManagement.Controllers
{
    public class CourseController : Controller
    {
        private CoureseContext db = new CoureseContext();

        // GET: Course
        public ActionResult Index(String name = "")
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }

            var courses = db.courses.Include(c => c.category).Where(a => a.course_name.Contains(name));
            return View(courses.ToList());
        }

        // GET: Course/Details/5
        public ActionResult Details(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cours cours = db.courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }


        // GET: Course/Create
        public ActionResult Create()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            ViewBag.category_id = new SelectList(db.categories, "id", "category_name");
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,course_name,description, short_description,category_id,start_date_plan, out_line")] cours cours)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (ModelState.IsValid)
            {
                db.courses.Add(cours);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.categories, "id", "category_name", cours.category_id);
            return View(cours);
        }

        // GET: Course/Edit/5
        public ActionResult Edit(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cours cours = db.courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.categories, "id", "category_name", cours.category_id);
            return View(cours);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "id,course_name,description, short_description,category_id,start_date_plan, out_line")] cours cours)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (ModelState.IsValid)
            {
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.categories, "id", "category_name", cours.category_id);
            return View(cours);
        }

        // GET: Course/Delete/5
        public ActionResult Delete(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cours cours = db.courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            cours cours = db.courses.Find(id);
            db.courses.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagement/ShopManagement/Controllers/HomepageController.cs
using CourseManagement.Models;
using CourseManagement.Models.CourseModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CourseManagement.Controllers
{
    public class HomepageController : Controller
    {
        private CoureseContext db = new CoureseContext();
        private CoureseContext courseContext = new CoureseContext();

        // GET: Homepage
        public ActionResult Index(int? category_id, string searchString)
        {
            ViewBag.categories = db.categories.ToList();
            ViewBag.courses = courseContext.courses.ToList();
         
            ViewBag.activeHome = "active";
            return View();
        }

        public ActionResult CourseDetail(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cours cours = db.courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            ViewBag.activeCourse = "active";
            ViewBag.courses_types = courseContext.courses_type.ToList();
            return View(cours);
        }

        // GET: Course
        public ActionResult Course(String name = "")
        {
           
            var courses = courseContext.courses;
            ViewBag.activeCourse = "active";
            return View(courses.ToList());
            
        }


        // GET: Homepage
        public ActionResult Contact()
        {
            ViewBag.categories = db.categories.ToList();
            ViewBag.branchs = db.branchs.ToList();
            ViewBag.activeContact = "active";
            return View();
        }

        // GET: Homepage
        public ActionResult Question()
        {
            ViewBag.activeQuestion = "active";
            ViewBag.questions = db.questions.ToList();
            return View();
        }

        // GET: Homepage
        public ActionResult About()
        {
            ViewBag.categories = db.categories.ToList();
            ViewBag.activeAbout = "active";
            ViewBag.abouts = courseContext.settings.Where(a => a.type == "about_us").First();
            ViewBag.abouts1 = courseContext.settings.Where(a => a.type == "about_us1").First();
            ViewBag.abouts2 = courseContext.settings.Where(a => a.type == "about_us2").First();
            ViewBag.abouts3 = courseContext.settings.Where(a => a.type == "about_us3").First();
            return View();
        }

        // GET: Homepage
        public ActionResult Login()
        {
            ViewBag.categories = db.categories.ToList();
            return View();
        }

        // GET: Homepage
        public ActionResult Register()
        {
            ViewBag.course_id = new SelectList(courseContext.courses, "id", "course_name");
            ViewBag.course_type_id = new SelectList(courseContext.courses_type.Select( c=> new
            {
                id = c.id,
                name = c.name + " - $" + c.price
            }), "id", "name");
            ViewBag.categories = db.categories.ToList();
            
            return View();
        }

        public ActionResult Search(string studentCode = "")
        {
            var student = db.students.Where(a => a.student_code.Equals(studentCode)).FirstOrDefault();
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.studentDetail = db.courses_student.Where(a => a.student_id == student.id && a.score > 0).ToList();
            ViewBag.activeAbout = "active";
            ViewBag.abouts = courseContext.settings.Where(a => a.type == "about_us").First();
            ViewBag.abouts1 = courseContext.settings.Where(a => a.type == "about_us1").First();
            ViewBag.abouts2 = courseContext.settings.Where(a => a.type == "about_us2").First();
            ViewBag.abouts3 = courseContext.settings.Where(a => a.type == "about_us3").First();
            return View();
        }

        // POST: StudentRegister/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "id,name,phone_number,email,address,date_of_birth,status,course_type_id,course_id,pracetice, payment_method")] students_register students_register)
        {
            if (ModelState.IsValid)
            {
                if(students_register.payment_method == 2)
                {
                    students_register.status = 2;
                    student student = new student();
                    student.student_name = students_register.name;                 
                    student.student_code = this.RandomString(10);
                    student.phone_number = students_register.phone_number;
                    student.email =     students_register.email;
                    student.address = students_register.address;
                    student.date_of_birth = students_register.date_of_birth;

                    db.students.Add(student);
                    courses_student courseStudent = new courses_student();
                    courseStudent.student_id = student.id;
                    courseStudent.course_id = students_register.course_id;
                    courseStudent.pracetice = students_register.pracetice;
                    db.courses_student.Add(courseStudent);
                } else
                {
                    students_register.status = 1;
                }
                
                db.students_register.Add(students_register);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.course_id = new SelectList(db.courses, "id", "course_name", students_register.course_id);
            ViewBag.course_type_id = new SelectList(db.courses_type, "id", "name", students_register.course_type_id);
            ViewBag.activeRegister = "active";
            return View(students_register);
        }
        // Generates a random string with a given size.    
        public string RandomString(int size, bool lowerCase = false)
        {
            var generator = new Random();
            var builder = new StringBuilder(size);

            // Unicode/ASCII Letters are divided into two blocks
            // (Letters 65–90 / 97–122):   
            // The first group containing the uppercase letters and
            // the second group containing the lowercase.  

            // char is a single Unicode character  
            char offset = lowerCase ? 'a' : 'A';
            const int lettersOffset = 26; // A...Z or a..z: length = 26  

            for (var i = 0; i < size; i++)
            {
                var @char = (char)generator.Next(offset, offset + lettersOffset);
                builder.Append(@char);
            }

            return lowerCase ? builder.ToString().ToLower() : builder.ToString();
        }
    }

   
}

CourseManagement/ShopManagement/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseManagement.Models.CourseModels;
using CourseManagement.Models;

namespace CourseManagement.Controllers
{
    public class QuestionController : Controller
    {
        private CoureseContext db = new CoureseContext();

        // GET: Question
        public ActionResult Index()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            return View(db.questions.ToList());
        }

        // GET: Question/Details/5
        public ActionResult Details(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Question/Create
        public ActionResult Create()
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            return View();
        }

        // POST: Question/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,question_name,description")] question question)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (ModelState.IsValid)
            {
                db.questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Question/Edit/5
        public ActionResult Edit(long? id)
        {
            if (!ValidateUser.IsUserLogin())
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Question/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,question_name,description")] question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Question/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Question/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            question question = db.questions.Find(id);
            db.questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CourseManagement/ShopManagement/Views/Homepage/Contact.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}



<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="banner_content text-center">
                        <h2>Contact Us</h2>
                        <div class="page_link">
                            <a href="index.html">Home</a>
                            <a href="contact.html">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<!--================Contact Area =================-->
<section class="contact_area section_gap">
    <div class="container">
        <div id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.319350036688!2d106.66408561471847!3d10.786834792314464!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ed2392c44df%3A0xd2ecb62e0d050fe9!2zRlBUIEFwdGVjaCBIQ00gLSBI4buHIFRo4buRbmcgxJDDoG8gVOG6oW8gTOG6rXAgVHLDrG5oIFZpw6puIFF14buRYyBU4bq_IChTaW5jZSAxOTk5KQ!5e0!3m2!1svi!2s!4v1650865980657!5m2!1svi!2s" width="1109" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        
        <div class="row">
         
            <div class="col-lg-12">
                <form class="row contact_form"
                      action="contact_process.php"
                      method="post"
                      id="contactForm"
                      novalidate="novalidate">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text"
                                   class="form-control"
                                   id="name"
                                   name="name"
                                   placeholder="Enter your name"
                                   onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Enter your name'"
                                   required="" />
                        </div>
                        <div class="form-group">
                            <input type="email"
                                   class="form-control"
                                   id="email"
                                   name="email"
                                   placeholder="Enter email address"
                                   onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Enter email address'"
                                   required="" />
                        </div>
                        <div class="form-group">
                            <input type="text"
                                   class="form-control"
                                   id="subject"
                                   name="subject"
                                   placeholder="Enter Subject"
                                   onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Enter Subject'"
                                   required="" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control"
                                      name="message"
                                      id="message"
                                      rows="1"
                                      placeholder="Enter Message"
                                      onfocus="this.placeholder = ''"
                                      onblur="this.placeholder = 'Enter Message'"
                                      required=""></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="btn primary-btn">
                            Send Message
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <hr />
        <div class="row">
            @foreach (var item in ViewBag.branchs)
            {
                <div class="col-lg-4" onclick="changeMap(@item.id)">
                    <div class="contact_info">
                        <div class="info_item">
                            <i class="ti-home"></i>
                            <h6>@item.address</h6>
                            <p>@item.branch_name</p>
                        </div>
                        <div class="info_item">
                            <i class="ti-headphone"></i>
                            <h6><a href="#">@item.phone_number</a></h6>
                        </div>
                        <div class="info_item">
                            <i class="ti-email"></i>
                            <h6><a href="#">@item.email</a></h6>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
    
</section>
<!--================Contact Area =================-->

CourseManagement/ShopManagement/Views/Homepage/Course.cshtml
@model IEnumerable<CourseManagement.Models.CourseModels.cours>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="banner_content text-center">
                        <h2>Courses</h2>
                        <div class="page_link">
                            <a href="index.html">Home</a>
                            <a href="courses.html">Courses</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<!--================ Start Popular Courses Area =================-->
<div class="popular_courses section_gap_top">
    <div class="container">
        <div class="row justify-content-center">
            <div >
                <div class="main_title">
                    <h2 class="mb-3">Our entrance exam</h2>
                    <p>
                        Our entrance exams take place twice a year in May and December. Based on your scores and wishes, we will arrange the right class to help you absorb the knowledge a best way. To register for our exam, you need to register for the course you want and we will send you the details.
                    </p>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="main_title">
                    <h2 class="mb-3">Our Courses</h2>
                    <p>
                        Replenish man have thing gathering lights yielding shall you
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- single course -->
            <div class="col-lg-12">
                <div class="owl-carousel active_course">
                    @foreach (var item in Model)
                    {
                        Random rand = new Random();
                        int number22 = rand.Next(1, 14);

                        <div class="single_course">
                            <div class="course_head">
                                <img class="img-fluid" src="@Url.Content("~/Content/user_course/img/courses/c" + number22 + ".jpg")" alt="" width="360" height="283" />
                            </div>
                            <div class="course_content">
                                
                                <span class="tag mb-4 d-inline-block">@item.category.category_name</span>
                                <h4 class="mb-3">
                                    <a href="@Url.Action("CourseDetail", "Homepage", new { id = item.id })">@item.course_name</a>
                                </h4>
                                <p>
                                    @item.short_description
                                </p>
                                
                            </div>
                        </div>
                    }


                </div>
            </div>
        </div>
    </div>
</div>
<!--================ End Popular Courses Area =================-->

CourseManagement/ShopManagement/Views/Homepage/Login.cshtml
@model CourseManagement.Models.user
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class="site-section">
    <div class="container">

        <div class="d-flex justify-content-center">
            @using (Html.BeginForm("Login", "Homepage", FormMethod.Post, new { @class = "user w-50" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Username" } })
                    @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.PasswordFor(model => model.password, new { @class = "form-control", @placeholder = "Password" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
                <input type="submit" class="btn btn-primary btn-user btn-block" value="Login">
                <div class="form-group text-center mt-2">
                    <a href="@Url.Action("Register")"><u>Register</u></a>
                </div>
                <div class="form-group text-center">
                    <a href="@Url.Action("Register")"><u>Forgot password? </u></a>
                </div>
                
            }
        </div>

    </div>
</div>

CourseManagement/ShopManagement/Views/Homepage/Question.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!--================ Start Home Banner Area =================-->
<section class="home_banner_area">
    <div class="banner_inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="banner_content text-center">
                        <p class="text-uppercase">
                            Best online education service In the world
                        </p>
                        <h2 class="text-uppercase mt-4 mb-5">
                            One Step Ahead This Season
                        </h2>
                        <div>
                            <a href="@Url.Action("Course", "Homepage")" class="primary-btn ml-sm-3 ml-0">see course</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================ End Home Banner Area =================-->
<!--================Blog Area =================-->
<section class="blog_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog_left_sidebar">
                    @foreach (var item in ViewBag.questions)
                    {
                        <article class="row blog_item">
                         
                            <div class="col-md-12">
                                <div class="blog_post">
                                   
                                    <div class="blog_details">
                                        <h2>@item.question_name</h2>
                                        <p>
                                           @item.description
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </article>
                    }

                    
                </div>
            </div>
            
        </div>
    </div>
</section>
<!--================Blog Area =================-->